#!/usr/bin/env bash
# Generate checks/config/config.gen.go from the upstream OpenTelemetry
# declarative-configuration JSON schema.
#
#
# Usage:
#   scripts/generate_config_schema.sh           # generate at HEAD
#   scripts/generate_config_schema.sh v1.1.0    # generate at a specific ref
#
# The output file has a "DO NOT EDIT" header; only helpers in
# config.go (Load, SignalEndpoints, ResourceAttributes, ExpandEnv) are
# hand-written.
set -euo pipefail

REF="${1:-main}"
SCHEMA_URL="https://raw.githubusercontent.com/open-telemetry/opentelemetry-configuration/${REF}/opentelemetry_configuration.json"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="${REPO_ROOT}/checks/config/config.gen.go"

# The upstream schema calls the root type "OpenTelemetryConfiguration".
# We rename it to "File" so the rest of the package can keep using the
# short, idiomatic Go name.
GENERATED_ROOT="OpenTelemetryConfiguration"
LOCAL_ROOT="File"

# Install go-jsonschema if it's not on PATH. Pinning to a known-good
# version so the regeneration is reproducible.
GO_JSONSCHEMA_VERSION="v0.24.1"
if ! command -v go-jsonschema >/dev/null 2>&1; then
    echo "installing go-jsonschema@${GO_JSONSCHEMA_VERSION}..." >&2
    go install "github.com/atombender/go-jsonschema@${GO_JSONSCHEMA_VERSION}"
fi

echo "fetching schema from ${SCHEMA_URL}" >&2
SCHEMA_TMP="$(mktemp -t otel-config-schema.XXXXXX.json)"
trap 'rm -f "${SCHEMA_TMP}"' EXIT
curl -sSfL "${SCHEMA_URL}" > "${SCHEMA_TMP}"

echo "generating ${OUTPUT}" >&2
GEN_TMP="$(mktemp -t otel-config-gen.XXXXXX.go)"
trap 'rm -f "${SCHEMA_TMP}" "${GEN_TMP}"' EXIT
go-jsonschema "${SCHEMA_TMP}" \
    --package config \
    --only-models \
    --tags yaml \
    --capitalization OTLP \
    --capitalization TLS \
    --capitalization URL \
    --capitalization HTTP \
    --capitalization ID \
    --struct-name-from-title \
    -o "${GEN_TMP}"

# Post-process: rename the schema's root type (and any derived
# wrapper types the generator emits with the same prefix, e.g.
# OpenTelemetryConfigurationDisabled → FileDisabled) to the shorter
# local name.
perl -i -pe "s/\\b${GENERATED_ROOT}/${LOCAL_ROOT}/g" "${GEN_TMP}"

{
    echo "// Code generated by scripts/generate_config_schema.sh from"
    echo "// ${SCHEMA_URL}"
    echo "// DO NOT EDIT — re-run the script to regenerate."
    echo
    tail -n +2 "${GEN_TMP}"  # skip the tool's own "Code generated by ..." line
} > "${OUTPUT}"

gofmt -w "${OUTPUT}"
echo "wrote ${OUTPUT} ($(wc -l < "${OUTPUT}") lines)" >&2
