name: Pull request checks

on: [pull_request]

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        with:
          persist-credentials: false
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1
        with:
          version: v2025.10.10
          sha256: e88762b61c243fbf472804feed0fd6d247ac0a5f17dc60778ef7dc2ec2d53a8a
      - name: Run checks
        run: mise run check
