name: Pull request checks

on: [pull_request]

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        with:
          persist-credentials: false
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          version: v2026.2.1
          sha256: 929126b055db71284d9c0ab87bdf1cca302ce4076fd693f01d7bd1916ff5f5c3
      - name: Run checks
        run: mise run check
